### PR TITLE
Feature Enhancements: Playlist Management

### PR DESCRIPTION
**Pull request by Pbgsa**
## Summary
This pull request introduces several new features related to playlist management. The implemented functionalities include:
- Creating a new playlist
- Deleting a playlist with ownership validation
- Adding songs to a playlist
- Changing the name of a playlist
- Removing a song from a playlist

Please note that there might be a conflict in the code due to a commented-out section that is currently failing. Another team member is addressing this issue. Just ignore the changes made in 'backend/src/tests/services/history.service.steps.ts' by me.

## Checklist
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No error nor warning in the console.

### CODE REVIEW

**Comment by Pbgsa** [comment]
You can keep all the changes made in 'playlist.controller.ts' it's ok. For the conflict in 'playlist.entity.ts' I recommend the following code and should work fine:
import BaseEntity from "./base.entity";

export default class PlaylistEntity extends BaseEntity {
  name: string;
  songs: string[]; // IDs das músicas na playlist
  createdBy: string; // ID do usuário que criou a playlist
  private: boolean;
  followers: string[]; // IDs dos usuários que seguem a playlist

  constructor(data: PlaylistEntity) {
    super(data.id || "");
    this.name = data.name;
    this.songs = data.songs || [];
    this.createdBy = data.createdBy;
    this.private = data.private || false;
    this.followers = data.followers || [];
  }
}

**Comment by aricneto** [comment]
> Please note that there might be a conflict in the code due to a commented-out section that is currently failing. Another team member is addressing this issue. Just ignore the changes made in 'backend/src/tests/services/history.service.steps.ts' by me.

please merge the current master branch to fix this issue so i can approve the PR

**Comment by Pbgsa** [comment]
> > Please note that there might be a conflict in the code due to a commented-out section that is currently failing. Another team member is addressing this issue. Just ignore the changes made in 'backend/src/tests/services/history.service.steps.ts' by me.
> 
> please merge the current master branch to fix this issue so i can approve the PR

Done. Could you review one more time?

**Review by aricneto — APPROVED** [review]
LGTM

**Pull request merged**
